import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import SmallHero from '../components/SmallHero';
import LargeHero from '../components/LargeHero';
import Services from '../components/Services';
import Encampasses from '../components/Encampasses';
import Testimonials from '../components/Testimonials';
import FAQs from '../components/FAQs';
// import "~bootstrap/dist/css/bootstap.css";


const Home: NextPage = () => {
  // const em = (e: any) => {
  //   console.log(e);

  // }

  // #0E2536
  // #F6B47D
  return (
    <div >
      <Head>
        <title>Home | BnB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SmallHero />
        <LargeHero />
        <Services />
        <Encampasses />
        <Testimonials />
        <FAQs />


      </main>
    </div >
  )
}

export default Home
